  $(function(){
    $('.jubu').eq(0).click(function(){
      $('.bbb').eq(0).children().toggle();
      $('.fangxing').eq(0).toggle()
      $('.sanjiao6').eq(0).toggle()
       $('.sanjiao7').eq(0).toggle()
    })
      $('.jubu').eq(1).click(function(){
      $('.bbb').eq(1).children().toggle();
      $('.fangxing').eq(1).toggle()
      $('.sanjiao6').eq(1).toggle()
       $('.sanjiao7').eq(1).toggle()
    })
        $('.jubu').eq(2).click(function(){
      $('.bbb').eq(2).children().toggle();
      $('.fangxing').eq(2).toggle()
      $('.sanjiao6').eq(2).toggle()
       $('.sanjiao7').eq(2).toggle()
    })
          $('.jubu').eq(3).click(function(){
      $('.bbb').eq(3).children().toggle();
      $('.fangxing').eq(3).toggle()
      $('.sanjiao6').eq(3).toggle()
       $('.sanjiao7').eq(3).toggle()
    })
            $('.jubu').eq(4).click(function(){
      $('.bbb').eq(4).children().toggle();
      $('.fangxing').eq(4).toggle()
      $('.sanjiao6').eq(4).toggle()
       $('.sanjiao7').eq(4).toggle()
    })
              $('.jubu').eq(5).click(function(){
      $('.bbb').eq(5).children().toggle();
      $('.fangxing').eq(5).toggle()
      $('.sanjiao6').eq(5).toggle()
       $('.sanjiao7').eq(5).toggle()
    })
                $('.jubu').eq(6).click(function(){
      $('.bbb').eq(6).children().toggle();
      $('.fangxing').eq(6).toggle()
      $('.sanjiao6').eq(6).toggle()
       $('.sanjiao7').eq(6).toggle()
    })
                  $('.jubu').eq(7).click(function(){
      $('.bbb').eq(7).children().toggle();
      $('.fangxing').eq(7).toggle()
      $('.sanjiao6').eq(7).toggle()
       $('.sanjiao7').eq(7).toggle()
    })
                    $('.jubu').eq(8).click(function(){
      $('.bbb').eq(8).children().toggle();
      $('.fangxing').eq(8).toggle()
      $('.sanjiao6').eq(8).toggle()
       $('.sanjiao7').eq(8).toggle()
    })
     $('.jubu').eq(9).click(function(){
      $('.bbb').eq(9).children().toggle();
      $('.fangxing').eq(9).toggle()
      $('.sanjiao6').eq(9).toggle()
       $('.sanjiao7').eq(9).toggle()
    })
     $('.jubu').eq(10).click(function(){
      $('.bbb').eq(10).children().toggle();
      $('.fangxing').eq(10).toggle()
      $('.sanjiao6').eq(10).toggle()
       $('.sanjiao7').eq(10).toggle()
    })
       $('.jubu').eq(11).click(function(){
      $('.bbb').eq(11).children().toggle();
      $('.fangxing').eq(11).toggle()
      $('.sanjiao6').eq(11).toggle()
       $('.sanjiao7').eq(11).toggle()
    })
     $('.jubu').eq(12).click(function(){
      $('.bbb').eq(12).children().toggle();
      $('.fangxing').eq(12).toggle()
      $('.sanjiao6').eq(12).toggle()
       $('.sanjiao7').eq(12).toggle()
    })
     $('.jubu').eq(13).click(function(){
      $('.bbb').eq(13).children().toggle();
      $('.fangxing').eq(13).toggle()
      $('.sanjiao6').eq(13).toggle()
       $('.sanjiao7').eq(13).toggle()
    })
     $('.jubu').eq(14).click(function(){
      $('.bbb').eq(14).children().toggle();
      $('.fangxing').eq(14).toggle()
      $('.sanjiao6').eq(14).toggle()
       $('.sanjiao7').eq(14).toggle()
    })
      $('.jubu').eq(15).click(function(){
      $('.bbb').eq(15).children().toggle();
      $('.fangxing').eq(15).toggle()
      $('.sanjiao6').eq(15).toggle()
       $('.sanjiao7').eq(15).toggle()
    })
        $('.jubu').eq(16).click(function(){
      $('.bbb').eq(16).children().toggle();
      $('.fangxing').eq(16).toggle()
      $('.sanjiao6').eq(16).toggle()
       $('.sanjiao7').eq(16).toggle()
    })
       $('.jubu').eq(17).click(function(){
      $('.bbb').eq(17).children().toggle();
      $('.fangxing').eq(17).toggle()
      $('.sanjiao6').eq(17).toggle()
       $('.sanjiao7').eq(17).toggle()
    })
     $('.jubu').eq(18).click(function(){
      $('.bbb').eq(18).children().toggle();
      $('.fangxing').eq(18).toggle()
      $('.sanjiao6').eq(18).toggle()
       $('.sanjiao7').eq(18).toggle()
    })
       $('.jubu').eq(19).click(function(){
      $('.bbb').eq(19).children().toggle();
      $('.fangxing').eq(19).toggle()
      $('.sanjiao6').eq(19).toggle()
       $('.sanjiao7').eq(19).toggle()
    })
  })
// shouji
// 
// 
 $(function(){
  $('.jubu-right111').eq(0).click(function(){
     $('.shouji-top').eq(0).toggle()
     $('.sanjiao8').eq(0).toggle()
     $('.sanjiao9').eq(0).toggle()
  })
   $('.jubu-right111').eq(1).click(function(){
     $('.shouji-top').eq(1).toggle()
     $('.sanjiao8').eq(1).toggle()
     $('.sanjiao9').eq(1).toggle()
  })
      $('.jubu-right111').eq(2).click(function(){
     $('.shouji-top').eq(2).toggle()
     $('.sanjiao8').eq(2).toggle()
     $('.sanjiao9').eq(2).toggle()
  })
         $('.jubu-right111').eq(3).click(function(){
     $('.shouji-top').eq(3).toggle()
     $('.sanjiao8').eq(3).toggle()
     $('.sanjiao9').eq(3).toggle()
  })
     $('.jubu-right111').eq(4).click(function(){
     $('.shouji-top').eq(4).toggle()
     $('.sanjiao8').eq(4).toggle()
     $('.sanjiao9').eq(4).toggle()
  })
   $('.jubu-right111').eq(5).click(function(){
     $('.shouji-top').eq(5).toggle()
     $('.sanjiao8').eq(5).toggle()
     $('.sanjiao9').eq(5).toggle()
  })
      $('.jubu-right111').eq(6).click(function(){
     $('.shouji-top').eq(6).toggle()
     $('.sanjiao8').eq(6).toggle()
     $('.sanjiao9').eq(6).toggle()
  })
    $('.jubu-right111').eq(7).click(function(){
     $('.shouji-top').eq(7).toggle()
     $('.sanjiao8').eq(7).toggle()
     $('.sanjiao9').eq(7).toggle()
  })
    $('.jubu-right111').eq(8).click(function(){
     $('.shouji-top').eq(8).toggle()
     $('.sanjiao8').eq(8).toggle()
     $('.sanjiao9').eq(8).toggle()
  })
   $('.jubu-right111').eq(9).click(function(){
     $('.shouji-top').eq(9).toggle()
     $('.sanjiao8').eq(9).toggle()
     $('.sanjiao9').eq(9).toggle()
  })
   $('.jubu-right111').eq(10).click(function(){
     $('.shouji-top').eq(10).toggle()
     $('.sanjiao8').eq(10).toggle()
     $('.sanjiao9').eq(10).toggle()
  })
     $('.jubu-right111').eq(11).click(function(){
     $('.shouji-top').eq(11).toggle()
     $('.sanjiao8').eq(11).toggle()
     $('.sanjiao9').eq(11).toggle()
  })
    $('.jubu-right111').eq(12).click(function(){
     $('.shouji-top').eq(12).toggle()
     $('.sanjiao8').eq(12).toggle()
     $('.sanjiao9').eq(12).toggle()
  })
$('.jubu-right111').eq(13).click(function(){
     $('.shouji-top').eq(13).toggle()
     $('.sanjiao8').eq(13).toggle()
     $('.sanjiao9').eq(13).toggle()
  })
   $('.jubu-right111').eq(14).click(function(){
     $('.shouji-top').eq(14).toggle()
     $('.sanjiao8').eq(14).toggle()
     $('.sanjiao9').eq(14).toggle()
  })
      $('.jubu-right111').eq(15).click(function(){
     $('.shouji-top').eq(15).toggle()
     $('.sanjiao8').eq(15).toggle()
     $('.sanjiao9').eq(15).toggle()
  })
         $('.jubu-right111').eq(16).click(function(){
     $('.shouji-top').eq(16).toggle()
     $('.sanjiao8').eq(16).toggle()
     $('.sanjiao9').eq(16).toggle()
  })
            $('.jubu-right111').eq(17).click(function(){
     $('.shouji-top').eq(17).toggle()
     $('.sanjiao8').eq(17).toggle()
     $('.sanjiao9').eq(17).toggle()
  })
               $('.jubu-right111').eq(18).click(function(){
     $('.shouji-top').eq(18).toggle()
     $('.sanjiao8').eq(18).toggle()
     $('.sanjiao9').eq(18).toggle()
  })
                  $('.jubu-right111').eq(19).click(function(){
     $('.shouji-top').eq(19).toggle()
     $('.sanjiao8').eq(19).toggle()
     $('.sanjiao9').eq(19).toggle()
  })
                     $('.jubu-right111').eq(20).click(function(){
     $('.shouji-top').eq(20).toggle()
     $('.sanjiao8').eq(20).toggle()
     $('.sanjiao9').eq(20).toggle()
  })
 })
